spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wazard?autoReconnect=true&setTimezone=Asia/Seoul
    username: root
    password: jk670403
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.naver.com
    port: 465
    username: diejeadong@naver.com
    password: jinmg670403
    properties:
      mail:
        smtp:
          enable: true
          required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            trust: smtp.naver.com
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jwt:
    header: Authorization
    atkKey: wazardAccessTokenKey1234567890qwertyasdfgWHDGKQTJFRPVMFHWPRXMwhdgkqtjfrPvmfhwprxm
    live:
      atk: 30000 #43200000  # 12시간

logging:
  level:
    org.hibernate.SQL: debug
    root: info